# Generated by Django 6.0.7 on 2026-07-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
