# Generated by Django 6.0.7 on 2026-08-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_is_system_chat_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='show_streak',
            field=models.BooleanField(default=True),
        ),
    ]
