# Generated by Django 6.0.7 on 2026-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_show_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapuser',
            name='ghost_mode',
            field=models.BooleanField(default=False),
        ),
    ]
